version: '3.4'
services:
  api:
    user: ${USER_ID}:${GROUP_ID}
    image: snomed_api:development
    build:
      args:
        - NODE_VERSION
      context: .
      dockerfile: ./build/api
    depends_on:
      - database
    volumes:
      - "${ROOT_CONTEXT}:/usr/app/snomed"
    networks:
      default:
        aliases:
          - snomed-api
      tuatha-de-danann:
        aliases:
          - snomed-api

  database:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - target: 5432
        published: 6100
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB=snomed-dev
      - POSTGRES_USER=snomed-dev
      - POSTGRES_PASSWORD=test
    networks:
      default:
        aliases:
          - snomed-db

networks:
  default:
  tuatha-de-danann:
    external: true
