version: '3.4'
services:
  api:
    user: ${USER_ID}:${GROUP_ID}
    build:
      args:
        - NODE_VERSION
      context: .
    depends_on:
      - database
    volumes:
      - "${PWD}:/usr/app/snomed"
    networks:
      default:
        aliases:
          - snomed-api
      tuatha-de-danann:
        aliases:
          - snomed-api

  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=snomed-dev
      - POSTGRES_USER=snomed-dev
      - POSTGRES_PASSWORD=test
    networks:
      default:
        aliases:
          - snomed-db

networks:
  default:
  tuatha-de-danann:
    external: true
