'use strict'

import config from '../config/environment'
import Sequelize from 'sequelize'
import Associations from './association'

const db = {
  Sequelize,
  sequelize: new Sequelize(config.sequelize.database, config.sequelize.username, config.sequelize.password, config.sequelize.options)
}

db.Address = db.sequelize.import('./model/address.model')
db.AllergyIntolerance = db.sequelize.import('./model/allergyIntolerance.model')
db.Appointment = db.sequelize.import('./model/appointment.model')
db.AppointmentStatusAudit = db.sequelize.import('./model/appointmentStatusAudit.model')
db.Attachment = db.sequelize.import('./model/attachment.model')
db.Condition = db.sequelize.import('./model/condition.model')
db.ConditionIsChronicAudit = db.sequelize.import('./model/conditionIsChronicAudit.model')
db.ConditionClinicalStatusAudit = db.sequelize.import('./model/conditionClinicalStatusAudit.model')
db.ConditionVerificationStatusAudit = db.sequelize.import('./model/conditionVerificationStatusAudit.model')
db.ConditionObservationsAudit = db.sequelize.import('./model/conditionObservationsAudit.model')
db.Contact = db.sequelize.import('./model/contact.model')
db.Drug = db.sequelize.import('./model/drug.model')
db.Encounter = db.sequelize.import('./model/encounter.model')
db.EpisodeOfCare = db.sequelize.import('./model/episodeOfCare.model')
db.EpisodeOfCareCareManagerAudit = db.sequelize.import('./model/episodeOfCareCareManagerAudit.model')
db.EpisodeOfCareDisplayInformationAudit = db.sequelize.import('./model/episodeOfCareDisplayInformationAudit.model')
db.EpisodeOfCarePriorityAudit = db.sequelize.import('./model/episodeOfCarePriorityAudit.model')
db.EpisodeOfCareStatusAudit = db.sequelize.import('./model/episodeOfCareStatusAudit.model')
db.Family = db.sequelize.import('./model/family.model')
db.ICDAlias = db.sequelize.import('./model/icdAlias.model')
db.ICDChapter = db.sequelize.import('./model/icdChapter.model')
db.ICDDisease = db.sequelize.import('./model/icdDisease.model')
db.ICDGroup = db.sequelize.import('./model/icdGroup.model')
db.ICDSection = db.sequelize.import('./model/icdSection.model')
db.ICDSubgroup = db.sequelize.import('./model/icdSubgroup.model')
db.ImmunizationRequest = db.sequelize.import('./model/immunizationRequest.model')
db.Insurance = db.sequelize.import('./model/insurance.model')
db.Location = db.sequelize.import('./model/location.model')
db.Medication = db.sequelize.import('./model/medication.model')
db.MedicationRequest = db.sequelize.import('./model/medicationRequest.model')
db.MedicationRequestPriorityAudit = db.sequelize.import('./model/medicationRequestPriorityAudit.model')
db.MedicationRequestStatusAudit = db.sequelize.import('./model/medicationRequestStatusAudit.model')
db.Name = db.sequelize.import('./model/name.model')
db.NurseIndication = db.sequelize.import('./model/nurseIndication.model')
db.NurseIndicationEncounters = db.sequelize.import('./model/nurseIndicationEncounters.model')
db.Patient = db.sequelize.import('./model/patient.model')
db.PatientInsurance = db.sequelize.import('./model/patientInsurance.model')
db.PCSAlias = db.sequelize.import('./model/pcsAlias.model')
db.PCSApproach = db.sequelize.import('./model/pcsApproach.model')
db.PCSBodyPart = db.sequelize.import('./model/pcsBodyPart.model')
db.PCSBodySystem = db.sequelize.import('./model/pcsBodySystem.model')
db.PCSDevice = db.sequelize.import('./model/pcsDevice.model')
db.PCSOperation = db.sequelize.import('./model/pcsOperation.model')
db.PCSProcedure = db.sequelize.import('./model/pcsProcedure.model')
db.PCSQualifier = db.sequelize.import('./model/pcsQualifier.model')
db.PCSSection = db.sequelize.import('./model/pcsSection.model')
db.PersonalHistory = db.sequelize.import('./model/personalHistory.model')
db.Practitioner = db.sequelize.import('./model/practitioner.model')
db.ProblemHistory = db.sequelize.import('./model/problemHistory.model')
db.ProcedureRequest = db.sequelize.import('./model/procedureRequest.model')
db.ProcedureRequestStatusAudit = db.sequelize.import('./model/procedureRequestStatusAudit.model')
db.ProcedureRequestPriorityAudit = db.sequelize.import('./model/procedureRequestPriorityAudit.model')
db.ProcedureRequestNoteAudit = db.sequelize.import('./model/procedureRequestNoteAudit.model')
db.ProcedureRequestOccurrenceDateTimeAudit = db.sequelize.import('./model/procedureRequestOccurrenceDateTimeAudit.model')
db.ProcedureRequestPerformerAudit = db.sequelize.import('./model/procedureRequestPerformerAudit.model')
db.QueueSlot = db.sequelize.import('./model/queueSlot.model')
db.QueueSlotStatusAudit = db.sequelize.import('./model/queueSlotStatusAudit.model')
db.SNOMEDConcept = db.sequelize.import('./model/snomedConcept.model')
db.SNOMEDDescription = db.sequelize.import('./model/snomedDescription.model')
db.SNOMEDRelationship = db.sequelize.import('./model/snomedRelationship.model')
db.SNOMEDTextDefinition = db.sequelize.import('./model/snomedTextDefinition.model')
db.SNOMEDStatedRelationship = db.sequelize.import('./model/snomedStatedRelationship.model')
db.Specialty = db.sequelize.import('./model/specialty.model')
db.Telecom = db.sequelize.import('./model/telecom.model')
db.User = db.sequelize.import('./model/user.model')
db.Vaccine = db.sequelize.import('./model/vaccine.model')

Associations(db)

module.exports = db
