version: '3.4'
services:
  api:
    image: snomed-api
    build:
      context: .
      args:
        - NODE_VERSION
      dockerfile: image/build/snomed-api
    restart: unless-stopped
    depends_on:
      - database
    networks:
      data:
        aliases:
          - snomed-api
      tuatha-de-danann:
        aliases:
          - snomed-api
    volumes:
      - "${STORAGE_DIR}/logs:/usr/app/snomed/logs"
      - "/etc/secrets/snomed/db.conf.js:/etc/secrets/snomed/db.conf.js:ro"

  database:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD_FILE
    networks:
      data:
        aliases:
          - snomed-db
    volumes:
      - "${STORAGE_DIR}/data:/var/lib/postgresql/data"
      - "/etc/secrets/snomed/pgpass:/etc/secrets/snomed/pgpass:ro"

networks:
  data:
  tuatha-de-danann:
    external: true
